// Pre-populated demo data for static / offline portfolio mode

export const DEMO_USER = {
  uid: 'demo-gamer-001',
  email: 'demo@loreboards.dev',
  displayName: 'Alex Rivers',
  username: 'AlexR',
  photoData: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" viewBox="0 0 100 100"><rect width="100" height="100" fill="%236C5CE7"/><text x="50%" y="55%" dominant-baseline="middle" text-anchor="middle" fill="white" font-family="sans-serif" font-size="42" font-weight="bold">A</text></svg>',
  isDemo: true,
};

export const INITIAL_DEMO_SUBMISSIONS = [
  {
    id: "demo-sub-1",
    userId: "demo-gamer-001",
    gameId: "igdb_119133",
    igdbId: "119133",
    title: "Elden Ring",
    platform: "PlayStation 5",
    developer: "FromSoftware",
    year: "2022",
    imageUrl: "https://images.igdb.com/igdb/image/upload/t_cover_big/co4jni.jpg",
    completionType: "Progress",
    completionValue: "100% Story",
    playerNotes: "Defeated every remembrance boss and earned the Lord of Frenzied Flame ending. Malenia took 4 hours, but what an absolute masterpiece!",
    source: "igdb",
    userDisplayName: "Alex Rivers",
    userUsername: "AlexR",
    userPhoto: DEMO_USER.photoData,
    createdAt: "2026-07-20T15:30:47.165Z"
  },
  {
    id: "demo-sub-2",
    userId: "demo-user-002",
    gameId: "igdb_112875",
    igdbId: "112875",
    title: "God of War Ragnarök",
    platform: "PlayStation 5",
    developer: "Santa Monica Studio",
    year: "2022",
    imageUrl: "https://images.igdb.com/igdb/image/upload/t_cover_big/coba3d.jpg",
    completionType: "Progress",
    completionValue: "100% Platinum",
    playerNotes: "Conquered the Nine Realms and completed Valhalla. The Kratos and Atreus story arc is unforgettable.",
    source: "igdb",
    userDisplayName: "Elena Rostova",
    userUsername: "ElenaR",
    userPhoto: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" viewBox="0 0 100 100"><rect width="100" height="100" fill="%23FF7675"/><text x="50%" y="55%" dominant-baseline="middle" text-anchor="middle" fill="white" font-family="sans-serif" font-size="42" font-weight="bold">E</text></svg>',
    createdAt: "2026-07-20T03:30:47.165Z"
  },
  {
    id: "demo-sub-3",
    userId: "demo-gamer-001",
    gameId: "igdb_113112",
    igdbId: "113112",
    title: "Hades",
    platform: "PC",
    developer: "Supergiant Games",
    year: "2020",
    imageUrl: "https://images.igdb.com/igdb/image/upload/t_cover_big/cob9kr.jpg",
    completionType: "High-Score",
    completionValue: "32 Heat",
    playerNotes: "Escaped Underworld on 32 Heat with the aspect of Arthur. Supergiant outdid themselves with combat flow!",
    source: "igdb",
    userDisplayName: "Alex Rivers",
    userUsername: "AlexR",
    userPhoto: DEMO_USER.photoData,
    createdAt: "2026-07-19T15:30:47.166Z"
  },
  {
    id: "demo-sub-4",
    userId: "demo-user-003",
    gameId: "igdb_119388",
    igdbId: "119388",
    title: "The Legend of Zelda: Tears of the Kingdom",
    platform: "Nintendo Switch",
    developer: "Nintendo",
    year: "2023",
    imageUrl: "https://images.igdb.com/igdb/image/upload/t_cover_big/co5vmg.jpg",
    completionType: "Progress",
    completionValue: "152 Shrines",
    playerNotes: "Built ridiculous Zonai contraptions to trivialize half the shrines. Ultrahand is game-changing.",
    source: "igdb",
    userDisplayName: "Marcus Vance",
    userUsername: "MVance",
    userPhoto: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" viewBox="0 0 100 100"><rect width="100" height="100" fill="%2300CEC9"/><text x="50%" y="55%" dominant-baseline="middle" text-anchor="middle" fill="white" font-family="sans-serif" font-size="42" font-weight="bold">M</text></svg>',
    createdAt: "2026-07-18T15:30:47.166Z"
  }
];
