// Centralized simulated users and submissions pool

export const DEMO_USER = {
  uid: 'demo-gamer-001',
  email: 'demo@loreboards.dev',
  displayName: 'Rivers Cuomo',
  username: 'RiversC',
  photoData: require('../../assets/demo-avatar.png'),
  isDemo: true,
};

export const SIMULATED_USERS = {
  "sim-user-marcusw": {
    displayName: "Marcus Webb",
    username: "MarcusW",
    userPhoto: require('../../assets/simulated-users/avatar2.png')
  },
  "sim-user-priyas": {
    displayName: "Priya Sharma",
    username: "PriyaS",
    userPhoto: require('../../assets/simulated-users/avatar3.png')
  },
  "sim-user-jaket": {
    displayName: "Jake Thornton",
    username: "JakeT",
    userPhoto: require('../../assets/simulated-users/avatar4.png')
  },
  "sim-user-yukit": {
    displayName: "Yuki Tanaka",
    username: "YukiT",
    userPhoto: require('../../assets/simulated-users/avatar5.png')
  },
  "sim-user-elarav": {
    displayName: "Elara Voss",
    username: "ElaraV",
    userPhoto: require('../../assets/simulated-users/avatar1.png')
  },
  "sim-user-alexr": {
    displayName: "Alex Rivera",
    username: "AlexR",
    userPhoto: require('../../assets/simulated-users/avatar2.png')
  },
  "sim-user-mayal": {
    displayName: "Maya Lin",
    username: "MayaL",
    userPhoto: require('../../assets/simulated-users/avatar3.png')
  },
  "sim-user-jordant": {
    displayName: "Jordan Taylor",
    username: "JordanT",
    userPhoto: require('../../assets/simulated-users/avatar4.png')
  },
  "sim-user-samk": {
    displayName: "Sam Kazi",
    username: "SamK",
    userPhoto: require('../../assets/simulated-users/avatar5.png')
  },
  "sim-user-elenar": {
    displayName: "Elena Rostova",
    username: "ElenaR",
    userPhoto: require('../../assets/simulated-users/avatar1.png')
  },
  "sim-user-chloet": {
    displayName: "Chloe Tanaka",
    username: "ChloeT",
    userPhoto: require('../../assets/simulated-users/avatar2.png')
  },
  "sim-user-leoc": {
    displayName: "Leo Chen",
    username: "LeoC",
    userPhoto: require('../../assets/simulated-users/avatar3.png')
  },
  "sim-user-sarahj": {
    displayName: "Sarah Jenkins",
    username: "SarahJ",
    userPhoto: require('../../assets/simulated-users/avatar4.png')
  },
  "sim-user-davidk": {
    displayName: "David Kim",
    username: "DavidK",
    userPhoto: require('../../assets/simulated-users/avatar5.png')
  },
  "sim-user-sophiam": {
    displayName: "Sophia Martinez",
    username: "SophiaM",
    userPhoto: require('../../assets/simulated-users/avatar1.png')
  }
};

export const SIMULATED_FEED_SUBMISSIONS = [
  {
    "id": "sim-sub-scraped-100",
    "userId": "sim-user-marcusw",
    "gameId": "igdb_6351",
    "igdbId": "6351",
    "title": "Contra III: The Alien Wars",
    "platform": "Super Famicom",
    "developer": "Konami",
    "year": "1992",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co64pi.jpg",
    "completionType": "Progress",
    "completionValue": "Loop 1",
    "playerNotes": "Cleared the first loop without cheats. The run-and-gun pacing is still unmatched.",
    "source": "igdb",
    "createdAt": "2026-07-19T17:05:19.945Z"
  },
  {
    "id": "sim-sub-scraped-101",
    "userId": "sim-user-priyas",
    "gameId": "igdb_1714",
    "igdbId": "1714",
    "title": "Mega Man",
    "platform": "Family Computer",
    "developer": "Capcom",
    "year": "1987",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co5x4b.jpg",
    "completionType": "Progress",
    "completionValue": "Main Story",
    "playerNotes": "Took down Dr. Wily. The tight platforming and boss patterns made every stage feel rewarding.",
    "source": "igdb",
    "createdAt": "2026-07-19T18:05:20.773Z"
  },
  {
    "id": "sim-sub-scraped-102",
    "userId": "sim-user-jaket",
    "gameId": "igdb_6807",
    "igdbId": "6807",
    "title": "Ghosts 'n Goblins",
    "platform": "Arcade",
    "developer": "Capcom",
    "year": "1985",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co20fk.jpg",
    "completionType": "Progress",
    "completionValue": "First Loop",
    "playerNotes": "Survived the first loop. This game is punishing in the best possible way.",
    "source": "igdb",
    "createdAt": "2026-07-19T19:05:21.881Z"
  },
  {
    "id": "sim-sub-scraped-103",
    "userId": "sim-user-yukit",
    "gameId": "igdb_2751",
    "igdbId": "2751",
    "title": "Galaga",
    "platform": "Arcade",
    "developer": "Namco Limited",
    "year": "1981",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co6njq.jpg",
    "completionType": "High-Score",
    "completionValue": "1,000,000 Points",
    "playerNotes": "Hit the million mark. The dual-ship trick is game-changing once you figure it out.",
    "source": "igdb",
    "createdAt": "2026-07-19T20:05:22.701Z"
  },
  {
    "id": "sim-sub-scraped-104",
    "userId": "sim-user-elarav",
    "gameId": "igdb_1090",
    "igdbId": "1090",
    "title": "Donkey Kong Country",
    "platform": "Super Nintendo Entertainment System",
    "developer": "Rare",
    "year": "1994",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co70qn.jpg",
    "completionType": "High-Score",
    "completionValue": "Stage 4 Reached",
    "playerNotes": "Made it to the rivet stage. Jumpman's controls take some getting used to but it clicks.",
    "source": "igdb",
    "createdAt": "2026-07-19T21:05:23.930Z"
  },
  {
    "id": "sim-sub-scraped-105",
    "userId": "sim-user-marcusw",
    "gameId": "igdb_3601",
    "igdbId": "3601",
    "title": "Space Invaders",
    "platform": "Arcade",
    "developer": "Taito",
    "year": "1978",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/cobtmt.jpg",
    "completionType": "High-Score",
    "completionValue": "Wave 10",
    "playerNotes": "Cleared wave 10. The increasing speed as aliens die is pure brilliance in design.",
    "source": "igdb",
    "createdAt": "2026-07-19T22:05:24.852Z"
  },
  {
    "id": "sim-sub-scraped-106",
    "userId": "sim-user-priyas",
    "gameId": "igdb_332202",
    "igdbId": "332202",
    "title": "Bubble Bobble",
    "platform": "ZX Spectrum",
    "developer": "Taito Corporation",
    "year": "1987",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co9f68.jpg",
    "completionType": "Progress",
    "completionValue": "True Ending",
    "playerNotes": "Got the true ending. The bubble-trapping mechanic never gets old.",
    "source": "igdb",
    "createdAt": "2026-07-19T23:05:25.774Z"
  },
  {
    "id": "sim-sub-scraped-107",
    "userId": "sim-user-jaket",
    "gameId": "igdb_2195",
    "igdbId": "2195",
    "title": "Mike Tyson's Punch-Out!!",
    "platform": "Nintendo Entertainment System",
    "developer": "Nintendo R&D3",
    "year": "1987",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co6386.jpg",
    "completionType": "Progress",
    "completionValue": "Main Campaign",
    "playerNotes": "Finally beat Mr. Dream. Pattern recognition and pixel-perfect timing make this an art form.",
    "source": "igdb",
    "createdAt": "2026-07-20T00:05:26.693Z"
  },
  {
    "id": "sim-sub-scraped-108",
    "userId": "sim-user-yukit",
    "gameId": "igdb_2741",
    "igdbId": "2741",
    "title": "Duck Hunt",
    "platform": "Family Computer",
    "developer": "Nintendo R&D1",
    "year": "1984",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co42pf.jpg",
    "completionType": "High-Score",
    "completionValue": "Round 20",
    "playerNotes": "Made it to round 20. That dog was an inspiration for every gaming villain since.",
    "source": "igdb",
    "createdAt": "2026-07-20T01:05:27.617Z"
  },
  {
    "id": "sim-sub-scraped-109",
    "userId": "sim-user-elarav",
    "gameId": "igdb_2970",
    "igdbId": "2970",
    "title": "Battletoads",
    "platform": "Nintendo Entertainment System",
    "developer": "Rare",
    "year": "1991",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co4i2w.jpg",
    "completionType": "Progress",
    "completionValue": "Turbo Tunnel",
    "playerNotes": "Cleared the Turbo Tunnel. One of the hardest difficulty spikes in gaming history.",
    "source": "igdb",
    "createdAt": "2026-07-20T02:05:28.538Z"
  },
  {
    "id": "sim-sub-scraped-110",
    "userId": "sim-user-marcusw",
    "gameId": "igdb_3490",
    "igdbId": "3490",
    "title": "F-Zero",
    "platform": "Super Famicom",
    "developer": "Nintendo Entertainment Analysis & Development",
    "year": "1990",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co6ufz.jpg",
    "completionType": "Progress",
    "completionValue": "Grand Prix Champion",
    "playerNotes": "Won the Grand Prix on Master class. The sense of speed in 1990 was absolutely mind-blowing.",
    "source": "igdb",
    "createdAt": "2026-07-20T03:05:29.708Z"
  },
  {
    "id": "sim-sub-scraped-111",
    "userId": "sim-user-priyas",
    "gameId": "igdb_3480",
    "igdbId": "3480",
    "title": "Earthworm Jim",
    "platform": "Sega Mega Drive/Genesis",
    "developer": "Shiny Entertainment",
    "year": "1994",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co20g8.jpg",
    "completionType": "Progress",
    "completionValue": "100%",
    "playerNotes": "Full completion. The absurdist humor and tight controls made it stand out from every other platformer.",
    "source": "igdb",
    "createdAt": "2026-07-20T04:05:30.276Z"
  },
  {
    "id": "sim-sub-scraped-112",
    "userId": "sim-user-jaket",
    "gameId": "igdb_5452",
    "igdbId": "5452",
    "title": "Sonic CD",
    "platform": "Sega CD",
    "developer": "Sonic Team",
    "year": "1993",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co53t2.jpg",
    "completionType": "Progress",
    "completionValue": "Good Ending",
    "playerNotes": "Got the good ending by saving all the animals. The time travel mechanic is genuinely inventive.",
    "source": "igdb",
    "createdAt": "2026-07-20T05:05:31.303Z"
  },
  {
    "id": "sim-sub-scraped-113",
    "userId": "sim-user-yukit",
    "gameId": "igdb_6797",
    "igdbId": "6797",
    "title": "Sonic the Hedgehog 3",
    "platform": "Sega Mega Drive/Genesis",
    "developer": "Sonic Team",
    "year": "1994",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co1zut.jpg",
    "completionType": "Progress",
    "completionValue": "All Chaos Emeralds",
    "playerNotes": "Collected all Chaos Emeralds with Knuckles. The connected world with Sonic & Knuckles is epic.",
    "source": "igdb",
    "createdAt": "2026-07-20T06:05:32.085Z"
  },
  {
    "id": "sim-sub-scraped-114",
    "userId": "sim-user-elarav",
    "gameId": "igdb_4446",
    "igdbId": "4446",
    "title": "Columns",
    "platform": "Arcade",
    "developer": "Sega Enterprises, Ltd.",
    "year": "1990",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2897.jpg",
    "completionType": "High-Score",
    "completionValue": "Level 30 Reached",
    "playerNotes": "Hit level 30. Simpler than Tetris but hypnotic in its own right.",
    "source": "igdb",
    "createdAt": "2026-07-20T07:05:33.247Z"
  },
  {
    "id": "sim-sub-scraped-115",
    "userId": "sim-user-marcusw",
    "gameId": "igdb_2473",
    "igdbId": "2473",
    "title": "Disney's Aladdin",
    "platform": "Super Nintendo Entertainment System",
    "developer": "Capcom",
    "year": "1993",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co7fan.jpg",
    "completionType": "Progress",
    "completionValue": "Main Story",
    "playerNotes": "Beat Jafar. The Genesis version's fluid animation was jaw-dropping for its time.",
    "source": "igdb",
    "createdAt": "2026-07-20T08:05:33.861Z"
  },
  {
    "id": "sim-sub-scraped-116",
    "userId": "sim-user-priyas",
    "gameId": "igdb_45228",
    "igdbId": "45228",
    "title": "Disney's The Lion King: Simba's Mighty Adventure",
    "platform": "PlayStation",
    "developer": "Midway Studios Los Angeles",
    "year": "2000",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3d3n.jpg",
    "completionType": "Progress",
    "completionValue": "Main Story",
    "playerNotes": "Completed the story. Difficult platforming but the graphics and music were stunning.",
    "source": "igdb",
    "createdAt": "2026-07-20T09:05:34.681Z"
  },
  {
    "id": "sim-sub-scraped-117",
    "userId": "sim-user-jaket",
    "gameId": "igdb_1063",
    "igdbId": "1063",
    "title": "Kirby's Dream Land",
    "platform": "Game Boy",
    "developer": "HAL Laboratory",
    "year": "1992",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3ffy.jpg",
    "completionType": "Progress",
    "completionValue": "Extra Mode",
    "playerNotes": "Cleared Extra Mode. Short but charming — the start of an incredible franchise.",
    "source": "igdb",
    "createdAt": "2026-07-20T10:05:35.603Z"
  },
  {
    "id": "sim-sub-scraped-118",
    "userId": "sim-user-yukit",
    "gameId": "igdb_1103",
    "igdbId": "1103",
    "title": "Super Metroid",
    "platform": "Super Famicom",
    "developer": "Nintendo R&D1",
    "year": "1994",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co5osy.jpg",
    "completionType": "Progress",
    "completionValue": "Best Ending",
    "playerNotes": "Got the best ending with a fast clear time. Samus's reveal was gaming's greatest twist.",
    "source": "igdb",
    "createdAt": "2026-07-20T11:05:36.525Z"
  },
  {
    "id": "sim-sub-scraped-119",
    "userId": "sim-user-elarav",
    "gameId": "igdb_1134",
    "igdbId": "1134",
    "title": "Castlevania: Aria of Sorrow",
    "platform": "Game Boy Advance",
    "developer": "Konami Computer Entertainment Tokyo",
    "year": "2003",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/cob947.jpg",
    "completionType": "Progress",
    "completionValue": "Main Story",
    "playerNotes": "Defeated Dracula. The whip controls and candleabra-smashing loop never gets old.",
    "source": "igdb",
    "createdAt": "2026-07-20T12:05:37.691Z"
  },
  {
    "id": "sim-sub-scraped-120",
    "userId": "sim-user-marcusw",
    "gameId": "igdb_1244",
    "igdbId": "1244",
    "title": "Tekken 3",
    "platform": "Arcade",
    "developer": "Namco",
    "year": "1997",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co8d7q.jpg",
    "completionType": "Progress",
    "completionValue": "Arcade Mode",
    "playerNotes": "Cleared arcade mode as Jin. The leap from Tekken 2 to 3 is one of the biggest in series history.",
    "source": "igdb",
    "createdAt": "2026-07-20T13:05:38.600Z"
  },
  {
    "id": "sim-sub-scraped-121",
    "userId": "sim-user-priyas",
    "gameId": "igdb_6692",
    "igdbId": "6692",
    "title": "Tony Hawk's Pro Skater",
    "platform": "PlayStation",
    "developer": "Neversoft Entertainment",
    "year": "1999",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co1y79.jpg",
    "completionType": "High-Score",
    "completionValue": "Warehouse 500K Combo",
    "playerNotes": "500K combo in the Warehouse. Before THPS 2 existed, this blew every mind.",
    "source": "igdb",
    "createdAt": "2026-07-20T14:05:39.288Z"
  },
  {
    "id": "sim-sub-scraped-122",
    "userId": "sim-user-jaket",
    "gameId": "igdb_1594",
    "igdbId": "1594",
    "title": "Gran Turismo",
    "platform": "PlayStation",
    "developer": "Polyphony Digital",
    "year": "1997",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co6e10.jpg",
    "completionType": "Progress",
    "completionValue": "License B",
    "playerNotes": "Completed B License tests. The simulation depth was unlike anything consoles had seen before.",
    "source": "igdb",
    "createdAt": "2026-07-20T15:05:40.516Z"
  },
  {
    "id": "sim-sub-scraped-123",
    "userId": "sim-user-yukit",
    "gameId": "igdb_1186",
    "igdbId": "1186",
    "title": "Crash Bandicoot 2: Cortex Strikes Back",
    "platform": "PlayStation",
    "developer": "Naughty Dog",
    "year": "1997",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co82vt.jpg",
    "completionType": "Progress",
    "completionValue": "All Gems Collected",
    "playerNotes": "Collected every gem. The platforming improvements over the first game are massive.",
    "source": "igdb",
    "createdAt": "2026-07-20T16:05:41.235Z"
  },
  {
    "id": "sim-sub-scraped-124",
    "userId": "sim-user-elarav",
    "gameId": "igdb_1577",
    "igdbId": "1577",
    "title": "Spyro 2: Ripto's Rage!",
    "platform": "PlayStation",
    "developer": "Insomniac Games",
    "year": "1999",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3ktq.jpg",
    "completionType": "Progress",
    "completionValue": "120% Complete",
    "playerNotes": "120% completion. Ripto's Rage added so much depth and charm over the original.",
    "source": "igdb",
    "createdAt": "2026-07-20T17:05:42.155Z"
  },
  {
    "id": "sim-sub-scraped-125",
    "userId": "sim-user-marcusw",
    "gameId": "igdb_4696",
    "igdbId": "4696",
    "title": "Twisted Metal 2",
    "platform": "PlayStation",
    "developer": "SingleTrac",
    "year": "1996",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co9412.jpg",
    "completionType": "Progress",
    "completionValue": "Sweet Tooth Campaign",
    "playerNotes": "Cleared as Sweet Tooth. The destruction derby chaos of TM2 is still unmatched.",
    "source": "igdb",
    "createdAt": "2026-07-20T18:05:43.385Z"
  },
  {
    "id": "sim-sub-scraped-126",
    "userId": "sim-user-priyas",
    "gameId": "igdb_425",
    "igdbId": "425",
    "title": "Final Fantasy VIII",
    "platform": "PlayStation",
    "developer": "Square Product Development Division 1",
    "year": "1999",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2z7d.jpg",
    "completionType": "Progress",
    "completionValue": "Main Story",
    "playerNotes": "Finished the story. The junction system is controversial but I love it.",
    "source": "igdb",
    "createdAt": "2026-07-20T19:05:44.537Z"
  },
  {
    "id": "sim-sub-scraped-127",
    "userId": "sim-user-jaket",
    "gameId": "igdb_421",
    "igdbId": "421",
    "title": "Final Fantasy IX",
    "platform": "PlayStation",
    "developer": "Square USA",
    "year": "2000",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2unc.jpg",
    "completionType": "Progress",
    "completionValue": "100% Trophies",
    "playerNotes": "Full completion. A love letter to classic Final Fantasy wrapped in a gorgeous package.",
    "source": "igdb",
    "createdAt": "2026-07-20T20:05:45.620Z"
  },
  {
    "id": "sim-sub-scraped-128",
    "userId": "sim-user-yukit",
    "gameId": "igdb_1346",
    "igdbId": "1346",
    "title": "Xenogears",
    "platform": "PlayStation",
    "developer": "Square Product Development Division 3",
    "year": "1998",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/cobxj4.jpg",
    "completionType": "Progress",
    "completionValue": "Main Story",
    "playerNotes": "Finished the story. The philosophical depth and the Disc 2 pacing controversy are both real.",
    "source": "igdb",
    "createdAt": "2026-07-20T21:05:46.661Z"
  },
  {
    "id": "sim-sub-scraped-129",
    "userId": "sim-user-elarav",
    "gameId": "igdb_428",
    "igdbId": "428",
    "title": "Final Fantasy Tactics",
    "platform": "PlayStation",
    "developer": "Square Product Development Division 4",
    "year": "1997",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2yx4.jpg",
    "completionType": "Progress",
    "completionValue": "Main Story",
    "playerNotes": "Beat Altima. The class system and tactical depth set a bar that's rarely been matched.",
    "source": "igdb",
    "createdAt": "2026-07-20T22:05:47.891Z"
  },
  {
    "id": "sim-sub-scraped-130",
    "userId": "sim-user-marcusw",
    "gameId": "igdb_327",
    "igdbId": "327",
    "title": "Age of Empires II: The Age of Kings",
    "platform": "PC (Microsoft Windows)",
    "developer": "Ensemble Studios",
    "year": "1999",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co55xo.jpg",
    "completionType": "Progress",
    "completionValue": "William Wallace Campaign",
    "playerNotes": "Completed the William Wallace campaign. Still one of the greatest RTS games ever made.",
    "source": "igdb",
    "createdAt": "2026-07-20T23:05:48.813Z"
  },
  {
    "id": "sim-sub-scraped-131",
    "userId": "sim-user-priyas",
    "gameId": "igdb_245",
    "igdbId": "245",
    "title": "Command & Conquer: Red Alert 2",
    "platform": "PC (Microsoft Windows)",
    "developer": "Westwood Pacific",
    "year": "2000",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/coar4c.jpg",
    "completionType": "Progress",
    "completionValue": "GDI Campaign",
    "playerNotes": "Cleared the GDI campaign. Kane's FMV cutscenes were the pinnacle of real-time-strategy drama.",
    "source": "igdb",
    "createdAt": "2026-07-21T00:05:49.940Z"
  },
  {
    "id": "sim-sub-scraped-132",
    "userId": "sim-user-jaket",
    "gameId": "igdb_15",
    "igdbId": "15",
    "title": "Fallout 3",
    "platform": "PlayStation 3",
    "developer": "Bethesda Game Studios",
    "year": "2008",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co1ycw.jpg",
    "completionType": "Progress",
    "completionValue": "Main Story",
    "playerNotes": "Defeated The Master. The choice to talk the final boss into suicide is still genius writing.",
    "source": "igdb",
    "createdAt": "2026-07-21T01:05:50.662Z"
  },
  {
    "id": "sim-sub-scraped-133",
    "userId": "sim-user-yukit",
    "gameId": "igdb_14",
    "igdbId": "14",
    "title": "Fallout 2",
    "platform": "PC (Microsoft Windows)",
    "developer": "Black Isle Studios",
    "year": "1998",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co8ado.jpg",
    "completionType": "Progress",
    "completionValue": "Main Story",
    "playerNotes": "Destroyed the Enclave. The sheer scope and freedom of this CRPG was decades ahead of its time.",
    "source": "igdb",
    "createdAt": "2026-07-21T02:05:51.576Z"
  },
  {
    "id": "sim-sub-scraped-134",
    "userId": "sim-user-elarav",
    "gameId": "igdb_832",
    "igdbId": "832",
    "title": "Planescape: Torment",
    "platform": "PC (Microsoft Windows)",
    "developer": "Black Isle Studios",
    "year": "1999",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3ggb.jpg",
    "completionType": "Progress",
    "completionValue": "Main Story",
    "playerNotes": "Faced the Transcendent One. What can change the nature of a man? One of gaming's best questions.",
    "source": "igdb",
    "createdAt": "2026-07-21T03:05:52.500Z"
  },
  {
    "id": "sim-sub-scraped-135",
    "userId": "sim-user-marcusw",
    "gameId": "igdb_333",
    "igdbId": "333",
    "title": "Quake",
    "platform": "PC (Microsoft Windows)",
    "developer": "id Software",
    "year": "1996",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co9bg9.jpg",
    "completionType": "Progress",
    "completionValue": "Main Campaign",
    "playerNotes": "Beat Shub-Niggurath. The dark, oppressive atmosphere was pure Lovecraftian horror.",
    "source": "igdb",
    "createdAt": "2026-07-21T04:05:53.419Z"
  },
  {
    "id": "sim-sub-scraped-136",
    "userId": "sim-user-priyas",
    "gameId": "igdb_364",
    "igdbId": "364",
    "title": "Heroes of Might and Magic III: The Restoration of Erathia",
    "platform": "PC (Microsoft Windows)",
    "developer": "New World Computing",
    "year": "1999",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2a47.jpg",
    "completionType": "Progress",
    "completionValue": "Main Campaign",
    "playerNotes": "Completed the Restoration of Erathia campaign. Turn-based strategy perfection.",
    "source": "igdb",
    "createdAt": "2026-07-21T05:05:54.342Z"
  },
  {
    "id": "sim-sub-scraped-137",
    "userId": "sim-user-jaket",
    "gameId": "igdb_130",
    "igdbId": "130",
    "title": "Warcraft II: Tides of Darkness",
    "platform": "DOS",
    "developer": "Blizzard Entertainment",
    "year": "1995",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3wix.jpg",
    "completionType": "Progress",
    "completionValue": "Human Campaign",
    "playerNotes": "Cleared the Human campaign. The foundation for everything Blizzard built afterward.",
    "source": "igdb",
    "createdAt": "2026-07-21T06:05:55.569Z"
  },
  {
    "id": "sim-sub-scraped-138",
    "userId": "sim-user-yukit",
    "gameId": "igdb_236",
    "igdbId": "236",
    "title": "Myst",
    "platform": "PC (Microsoft Windows)",
    "developer": "Cyan Worlds",
    "year": "1993",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co1y96.jpg",
    "completionType": "Progress",
    "completionValue": "True Ending",
    "playerNotes": "Got the true ending. The mystery and atmosphere were unlike anything in gaming at the time.",
    "source": "igdb",
    "createdAt": "2026-07-21T07:05:56.286Z"
  },
  {
    "id": "sim-sub-scraped-139",
    "userId": "sim-user-elarav",
    "gameId": "igdb_330",
    "igdbId": "330",
    "title": "SimCity 2000",
    "platform": "Mac",
    "developer": "Maxis",
    "year": "1993",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co1o4d.jpg",
    "completionType": "Progress",
    "completionValue": "Megalopolis Achieved",
    "playerNotes": "Built a Megalopolis. The depth of the simulation was astounding for its era.",
    "source": "igdb",
    "createdAt": "2026-07-21T08:05:57.279Z"
  },
  {
    "id": "sim-sub-scraped-140",
    "userId": "sim-user-marcusw",
    "gameId": "igdb_2",
    "igdbId": "2",
    "title": "Thief: The Dark Project",
    "platform": "PC (Microsoft Windows)",
    "developer": "Looking Glass Studios",
    "year": "1998",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co22ne.jpg",
    "completionType": "Progress",
    "completionValue": "Expert Difficulty",
    "playerNotes": "Cleared on Expert. Immersive stealth gameplay that still defines the genre.",
    "source": "igdb",
    "createdAt": "2026-07-21T09:05:58.114Z"
  },
  {
    "id": "sim-sub-scraped-141",
    "userId": "sim-user-priyas",
    "gameId": "igdb_1172",
    "igdbId": "1172",
    "title": "Golden Sun",
    "platform": "Game Boy Advance",
    "developer": "Camelot Software Planning",
    "year": "2001",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co1uca.jpg",
    "completionType": "Progress",
    "completionValue": "Main Story",
    "playerNotes": "Defeated the bosses. The Djinn system made this the most compelling RPG on GBA.",
    "source": "igdb",
    "createdAt": "2026-07-21T10:05:58.949Z"
  },
  {
    "id": "sim-sub-scraped-142",
    "userId": "sim-user-jaket",
    "gameId": "igdb_1443",
    "igdbId": "1443",
    "title": "Fire Emblem Awakening",
    "platform": "Nintendo 3DS",
    "developer": "Nintendo SPD Production Group No. 2",
    "year": "2012",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/cobcko.jpg",
    "completionType": "Progress",
    "completionValue": "Main Story",
    "playerNotes": "Finished the story without losing a unit. Permadeath makes every decision meaningful.",
    "source": "igdb",
    "createdAt": "2026-07-21T11:05:59.871Z"
  },
  {
    "id": "sim-sub-scraped-143",
    "userId": "sim-user-yukit",
    "gameId": "igdb_1691",
    "igdbId": "1691",
    "title": "Advance Wars",
    "platform": "Game Boy Advance",
    "developer": "Intelligent Systems",
    "year": "2001",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/cob9nu.jpg",
    "completionType": "Progress",
    "completionValue": "Campaign",
    "playerNotes": "Cleared the full campaign. Turn-based tactical perfection in a portable package.",
    "source": "igdb",
    "createdAt": "2026-07-21T12:06:00.793Z"
  },
  {
    "id": "sim-sub-scraped-144",
    "userId": "sim-user-elarav",
    "gameId": "igdb_1132",
    "igdbId": "1132",
    "title": "Castlevania: Circle of the Moon",
    "platform": "Game Boy Advance",
    "developer": "Konami Computer Entertainment Kobe",
    "year": "2001",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/cobcr5.jpg",
    "completionType": "Progress",
    "completionValue": "Main Story",
    "playerNotes": "Beat Dracula. A worthy GBA launch title that kept the Symphony of the Night spirit alive.",
    "source": "igdb",
    "createdAt": "2026-07-21T13:06:01.713Z"
  },
  {
    "id": "sim-sub-scraped-145",
    "userId": "sim-user-marcusw",
    "gameId": "igdb_1107",
    "igdbId": "1107",
    "title": "Metroid: Zero Mission",
    "platform": "Game Boy Advance",
    "developer": "Nintendo R&D1",
    "year": "2004",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co1vci.jpg",
    "completionType": "Progress",
    "completionValue": "100% Items",
    "playerNotes": "100% item collection. The best introduction to Metroid and an upgrade in every way over the NES original.",
    "source": "igdb",
    "createdAt": "2026-07-21T14:06:02.532Z"
  },
  {
    "id": "sim-sub-scraped-146",
    "userId": "sim-user-priyas",
    "gameId": "igdb_5075",
    "igdbId": "5075",
    "title": "Nights Into Dreams...",
    "platform": "Sega Saturn",
    "developer": "Sonic Team",
    "year": "1996",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2n17.jpg",
    "completionType": "Progress",
    "completionValue": "A-Rank All Levels",
    "playerNotes": "A-Ranked every level. The dreamlike flight mechanic is unlike anything else on Saturn.",
    "source": "igdb",
    "createdAt": "2026-07-21T15:06:03.557Z"
  },
  {
    "id": "sim-sub-scraped-147",
    "userId": "sim-user-jaket",
    "gameId": "igdb_18696",
    "igdbId": "18696",
    "title": "Ridge Racer",
    "platform": "Arcade",
    "developer": "Namco",
    "year": "1993",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co20gc.jpg",
    "completionType": "Progress",
    "completionValue": "Grand Prix",
    "playerNotes": "Won the Grand Prix. The drifting mechanic was revelatory when this launched with the PlayStation.",
    "source": "igdb",
    "createdAt": "2026-07-21T16:06:04.479Z"
  },
  {
    "id": "sim-sub-scraped-148",
    "userId": "sim-user-yukit",
    "gameId": "igdb_1569",
    "igdbId": "1569",
    "title": "Jet Grind Radio",
    "platform": "Dreamcast",
    "developer": "Smilebit",
    "year": "2000",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3rjd.jpg",
    "completionType": "Progress",
    "completionValue": "100% Graffiti",
    "playerNotes": "Tagged everything. The cel-shading, soundtrack, and skating are a perfect combination.",
    "source": "igdb",
    "createdAt": "2026-07-21T17:06:05.195Z"
  },
  {
    "id": "sim-sub-scraped-149",
    "userId": "sim-user-elarav",
    "gameId": "igdb_1672",
    "igdbId": "1672",
    "title": "Panzer Dragoon Orta",
    "platform": "Xbox",
    "developer": "Smilebit",
    "year": "2002",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co68yo.jpg",
    "completionType": "Progress",
    "completionValue": "Main Campaign",
    "playerNotes": "Defeated the final boss. The rail-shooter format and world-building are breathtaking even today.",
    "source": "igdb",
    "createdAt": "2026-07-21T18:06:06.327Z"
  },
  {
    "id": "sim-sub-scraped-150",
    "userId": "sim-user-marcusw",
    "gameId": "igdb_1217",
    "igdbId": "1217",
    "title": "Shenmue",
    "platform": "Dreamcast",
    "developer": "Sega AM2",
    "year": "1999",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3wmr.jpg",
    "completionType": "Progress",
    "completionValue": "Chapter 1",
    "playerNotes": "Completed Chapter 1. The open-world detail and QTE system were groundbreaking for 1999.",
    "source": "igdb",
    "createdAt": "2026-07-21T19:06:07.242Z"
  },
  {
    "id": "sim-sub-scraped-51",
    "userId": "sim-user-alexr",
    "gameId": "igdb_885",
    "igdbId": "885",
    "title": "Super Meat Boy",
    "platform": "Xbox 360",
    "developer": "Team Meat",
    "year": "2010",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co276m.jpg",
    "completionType": "Progress",
    "completionValue": "Dark World 100%",
    "playerNotes": "100% completed all Dark World levels. Precision platforming at its absolute peak.",
    "source": "igdb",
    "createdAt": "2026-07-19T22:02:13.710Z"
  },
  {
    "id": "sim-sub-scraped-52",
    "userId": "sim-user-mayal",
    "gameId": "igdb_2132",
    "igdbId": "2132",
    "title": "The Binding of Isaac",
    "platform": "PC (Microsoft Windows)",
    "developer": "Edmund McMillen",
    "year": "2011",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co1qll.jpg",
    "completionType": "Progress",
    "completionValue": "Chest",
    "playerNotes": "Defeated Blue Baby in the Chest. Every run feels completely fresh with 500+ items.",
    "source": "igdb",
    "createdAt": "2026-07-19T23:02:14.521Z"
  },
  {
    "id": "sim-sub-scraped-53",
    "userId": "sim-user-jordant",
    "gameId": "igdb_7444",
    "igdbId": "7444",
    "title": "Shovel Knight",
    "platform": "Nintendo 3DS",
    "developer": "Yacht Club Games",
    "year": "2014",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/cobaa7.jpg",
    "completionType": "Progress",
    "completionValue": "Main Story",
    "playerNotes": "Beat the main campaign. Retro 8-bit aesthetic done with modern perfection.",
    "source": "igdb",
    "createdAt": "2026-07-20T00:02:15.442Z"
  },
  {
    "id": "sim-sub-scraped-54",
    "userId": "sim-user-samk",
    "gameId": "igdb_11182",
    "igdbId": "11182",
    "title": "Enter the Gungeon",
    "platform": "Mac",
    "developer": "Dodge Roll",
    "year": "2016",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/cobl6c.jpg",
    "completionType": "Progress",
    "completionValue": "Past Killed",
    "playerNotes": "Killed the Dragun and killed the past. Bullet hell roguelike goodness.",
    "source": "igdb",
    "createdAt": "2026-07-20T01:02:16.607Z"
  },
  {
    "id": "sim-sub-scraped-55",
    "userId": "sim-user-elenar",
    "gameId": "igdb_2853",
    "igdbId": "2853",
    "title": "Braid",
    "platform": "Xbox 360",
    "developer": "Number None Inc.",
    "year": "2008",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co25ni.jpg",
    "completionType": "Progress",
    "completionValue": "All Stars Collected",
    "playerNotes": "Collected all hidden stars. The time-manipulation puzzles and ending twist were mind-bending.",
    "source": "igdb",
    "createdAt": "2026-07-20T02:02:17.547Z"
  },
  {
    "id": "sim-sub-scraped-56",
    "userId": "sim-user-alexr",
    "gameId": "igdb_1991",
    "igdbId": "1991",
    "title": "Fez",
    "platform": "Xbox 360",
    "developer": "Polytron Corporation",
    "year": "2012",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co1rd9.jpg",
    "completionType": "Progress",
    "completionValue": "64 Cube Ending",
    "playerNotes": "Found all 32 anti-cubes. The 2D-to-3D perspective shift and cryptic puzzles are unmatched.",
    "source": "igdb",
    "createdAt": "2026-07-20T03:02:18.514Z"
  },
  {
    "id": "sim-sub-scraped-57",
    "userId": "sim-user-mayal",
    "gameId": "igdb_1331",
    "igdbId": "1331",
    "title": "Limbo",
    "platform": "Xbox 360",
    "developer": "Playdead",
    "year": "2010",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co1qrs.jpg",
    "completionType": "Progress",
    "completionValue": "Main Story",
    "playerNotes": "Finished the journey. Monochromatic, eerie atmosphere with brilliant environmental puzzles.",
    "source": "igdb",
    "createdAt": "2026-07-20T04:02:19.743Z"
  },
  {
    "id": "sim-sub-scraped-58",
    "userId": "sim-user-jordant",
    "gameId": "igdb_7342",
    "igdbId": "7342",
    "title": "Inside",
    "platform": "Xbox One",
    "developer": "Playdead",
    "year": "2016",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2fca.jpg",
    "completionType": "Progress",
    "completionValue": "Secret Ending",
    "playerNotes": "Discovered the hidden secret ending. That final section is one of the wildest moments in gaming.",
    "source": "igdb",
    "createdAt": "2026-07-20T05:02:20.666Z"
  },
  {
    "id": "sim-sub-scraped-59",
    "userId": "sim-user-samk",
    "gameId": "igdb_1384",
    "igdbId": "1384",
    "title": "Hotline Miami",
    "platform": "Linux",
    "developer": "Dennaton Games",
    "year": "2012",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co1vqp.jpg",
    "completionType": "Progress",
    "completionValue": "A+ All Chapters",
    "playerNotes": "A+ rank on every level. High-octane violence backed by an incredible synthwave soundtrack.",
    "source": "igdb",
    "createdAt": "2026-07-20T06:02:21.689Z"
  },
  {
    "id": "sim-sub-scraped-60",
    "userId": "sim-user-elenar",
    "gameId": "igdb_28512",
    "igdbId": "28512",
    "title": "Risk of Rain 2",
    "platform": "PC (Microsoft Windows)",
    "developer": "Hopoo Games",
    "year": "2020",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/coaavb.jpg",
    "completionType": "Progress",
    "completionValue": "Main Run",
    "playerNotes": "Escaped the moon after beating Mithrix. Stacking items until you feel godlike is addicting.",
    "source": "igdb",
    "createdAt": "2026-07-20T07:02:22.437Z"
  },
  {
    "id": "sim-sub-scraped-61",
    "userId": "sim-user-alexr",
    "gameId": "igdb_7046",
    "igdbId": "7046",
    "title": "Factorio",
    "platform": "PC (Microsoft Windows)",
    "developer": "Wube Software",
    "year": "2020",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co1tfy.jpg",
    "completionType": "Progress",
    "completionValue": "Rocket Launched",
    "playerNotes": "Launched the rocket. The factory must grow — 200 hours vanished without a trace.",
    "source": "igdb",
    "createdAt": "2026-07-20T08:02:23.429Z"
  },
  {
    "id": "sim-sub-scraped-62",
    "userId": "sim-user-mayal",
    "gameId": "igdb_9789",
    "igdbId": "9789",
    "title": "RimWorld",
    "platform": "Mac",
    "developer": "Ludeon Studios",
    "year": "2018",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/coaaqj.jpg",
    "completionType": "Progress",
    "completionValue": "Ship Escape",
    "playerNotes": "Built the ship and escaped. The emergent storytelling from colonist mental breaks is hilarious.",
    "source": "igdb",
    "createdAt": "2026-07-20T09:02:24.147Z"
  },
  {
    "id": "sim-sub-scraped-63",
    "userId": "sim-user-jordant",
    "gameId": "igdb_3075",
    "igdbId": "3075",
    "title": "FTL: Faster Than Light",
    "platform": "Linux",
    "developer": "Subset Games",
    "year": "2012",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co9chw.jpg",
    "completionType": "Progress",
    "completionValue": "Flagship Destroyed",
    "playerNotes": "Defeated the Rebel Flagship on Hard. Micro-managing power and crew under intense pressure.",
    "source": "igdb",
    "createdAt": "2026-07-20T10:02:24.863Z"
  },
  {
    "id": "sim-sub-scraped-64",
    "userId": "sim-user-samk",
    "gameId": "igdb_2935",
    "igdbId": "2935",
    "title": "Papers, Please",
    "platform": "Mac",
    "developer": "Lucas Pope",
    "year": "2013",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co1vep.jpg",
    "completionType": "Progress",
    "completionValue": "Ending 20 (Best)",
    "playerNotes": "GLORY TO ARSTOTZKA. Simple passport checking turned into a moral dilemma masterpiece.",
    "source": "igdb",
    "createdAt": "2026-07-20T11:02:25.890Z"
  },
  {
    "id": "sim-sub-scraped-65",
    "userId": "sim-user-elenar",
    "gameId": "igdb_9643",
    "igdbId": "9643",
    "title": "Return of the Obra Dinn",
    "platform": "PC (Microsoft Windows)",
    "developer": "Lucas Pope",
    "year": "2018",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co27j9.jpg",
    "completionType": "Progress",
    "completionValue": "60/60 Fates Identified",
    "playerNotes": "Correctly identified all 60 crew fates. Detective work at its finest.",
    "source": "igdb",
    "createdAt": "2026-07-20T12:02:26.810Z"
  },
  {
    "id": "sim-sub-scraped-66",
    "userId": "sim-user-alexr",
    "gameId": "igdb_186725",
    "igdbId": "186725",
    "title": "Vampire Survivors",
    "platform": "PC (Microsoft Windows)",
    "developer": "Poncle",
    "year": "2022",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co4bzv.jpg",
    "completionType": "Progress",
    "completionValue": "All Evolve Recipes",
    "playerNotes": "Unlocked every weapon evolution. The ultimate dopamine-dispensing bullet-heaven game.",
    "source": "igdb",
    "createdAt": "2026-07-20T13:02:27.824Z"
  },
  {
    "id": "sim-sub-scraped-67",
    "userId": "sim-user-mayal",
    "gameId": "igdb_251833",
    "igdbId": "251833",
    "title": "Balatro",
    "platform": "Xbox One",
    "developer": "LocalThunk",
    "year": "2024",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co9f4g.jpg",
    "completionType": "Progress",
    "completionValue": "Gold Stake Victory",
    "playerNotes": "Won on Gold Stake with the Ghost Deck. Poker roguelike deckbuilding perfection.",
    "source": "igdb",
    "createdAt": "2026-07-20T14:02:28.295Z"
  },
  {
    "id": "sim-sub-scraped-68",
    "userId": "sim-user-jordant",
    "gameId": "igdb_165351",
    "igdbId": "165351",
    "title": "Cult of the Lamb",
    "platform": "Xbox Series X|S",
    "developer": "Massive Monster",
    "year": "2022",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/cobbwj.jpg",
    "completionType": "Progress",
    "completionValue": "Main Campaign",
    "playerNotes": "Defeated One Who Waits. Perfectly blends dungeon crawling with cute cult management.",
    "source": "igdb",
    "createdAt": "2026-07-20T15:02:29.273Z"
  },
  {
    "id": "sim-sub-scraped-69",
    "userId": "sim-user-samk",
    "gameId": "igdb_139090",
    "igdbId": "139090",
    "title": "Inscryption",
    "platform": "Mac",
    "developer": "Daniel Mullins Games",
    "year": "2021",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co401c.jpg",
    "completionType": "Progress",
    "completionValue": "Act 3",
    "playerNotes": "Finished Leshy's game and beyond. The genre-shifting ARG elements were brilliant.",
    "source": "igdb",
    "createdAt": "2026-07-20T16:02:30.366Z"
  },
  {
    "id": "sim-sub-scraped-70",
    "userId": "sim-user-elenar",
    "gameId": "igdb_23733",
    "igdbId": "23733",
    "title": "Tunic",
    "platform": "Mac",
    "developer": "Andrew Shouldice",
    "year": "2022",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/td1t8kb33gyo8mvhl2pc.jpg",
    "completionType": "Progress",
    "completionValue": "Golden Path Solved",
    "playerNotes": "Decoded the manual and solved the Golden Path. Pure Zelda-inspired discovery magic.",
    "source": "igdb",
    "createdAt": "2026-07-20T17:02:31.419Z"
  },
  {
    "id": "sim-sub-scraped-71",
    "userId": "sim-user-alexr",
    "gameId": "igdb_144022",
    "igdbId": "144022",
    "title": "Sifu",
    "platform": "PlayStation 5",
    "developer": "Sloclap",
    "year": "2022",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co4h5s.jpg",
    "completionType": "Progress",
    "completionValue": "Wuguan Age 20",
    "playerNotes": "Spared all 5 bosses under age 20. Martial arts combat flow feels like a kung fu movie.",
    "source": "igdb",
    "createdAt": "2026-07-20T18:02:32.237Z"
  },
  {
    "id": "sim-sub-scraped-72",
    "userId": "sim-user-mayal",
    "gameId": "igdb_110248",
    "igdbId": "110248",
    "title": "Stray",
    "platform": "PC (Microsoft Windows)",
    "developer": "BlueTwelve Studio",
    "year": "2022",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co4tt2.jpg",
    "completionType": "Progress",
    "completionValue": "Outside Reached",
    "playerNotes": "Reached the surface. A charming adventure as a stray cat exploring a cyberpunk walled city.",
    "source": "igdb",
    "createdAt": "2026-07-20T19:02:33.244Z"
  },
  {
    "id": "sim-sub-scraped-73",
    "userId": "sim-user-jordant",
    "gameId": "igdb_3152",
    "igdbId": "3152",
    "title": "Don't Starve",
    "platform": "Linux",
    "developer": "Klei Entertainment",
    "year": "2013",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co1qqw.jpg",
    "completionType": "Progress",
    "completionValue": "Adventure Mode",
    "playerNotes": "Survived Maxwell's tests. Dark Tim Burton-esque art style with brutal survival mechanics.",
    "source": "igdb",
    "createdAt": "2026-07-20T20:02:34.182Z"
  },
  {
    "id": "sim-sub-scraped-74",
    "userId": "sim-user-samk",
    "gameId": "igdb_7886",
    "igdbId": "7886",
    "title": "Crypt of the NecroDancer",
    "platform": "PC (Microsoft Windows)",
    "developer": "Brace Yourself Games",
    "year": "2015",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/cobaog.jpg",
    "completionType": "Progress",
    "completionValue": "Zone 4",
    "playerNotes": "Moving to the beat of Danny Baranowsky's soundtrack never gets old.",
    "source": "igdb",
    "createdAt": "2026-07-20T21:02:35.412Z"
  },
  {
    "id": "sim-sub-scraped-75",
    "userId": "sim-user-elenar",
    "gameId": "igdb_6705",
    "igdbId": "6705",
    "title": "A Hat in Time",
    "platform": "Mac",
    "developer": "Gears for Breakfast",
    "year": "2017",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/cob1uc.jpg",
    "completionType": "Progress",
    "completionValue": "40 Time Pieces",
    "playerNotes": "Collected every Time Piece. Pure collectathon platformer joy with hilarious writing.",
    "source": "igdb",
    "createdAt": "2026-07-20T22:02:36.230Z"
  },
  {
    "id": "sim-sub-scraped-76",
    "userId": "sim-user-alexr",
    "gameId": "igdb_20150",
    "igdbId": "20150",
    "title": "Katana Zero",
    "platform": "Nintendo Switch",
    "developer": "Askiisoft",
    "year": "2019",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co1isp.jpg",
    "completionType": "Progress",
    "completionValue": "Hard Mode",
    "playerNotes": "Slash through rooms with zero mistakes in slow motion. Neo-noir masterpiece.",
    "source": "igdb",
    "createdAt": "2026-07-20T23:02:37.254Z"
  },
  {
    "id": "sim-sub-scraped-77",
    "userId": "sim-user-mayal",
    "gameId": "igdb_22917",
    "igdbId": "22917",
    "title": "Gris",
    "platform": "Nintendo Switch",
    "developer": "Nomada Studio",
    "year": "2018",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co1qv5.jpg",
    "completionType": "Progress",
    "completionValue": "100%",
    "playerNotes": "Restored color to the world. Breathtaking watercolor art direction and emotional score.",
    "source": "igdb",
    "createdAt": "2026-07-21T00:02:38.176Z"
  },
  {
    "id": "sim-sub-scraped-78",
    "userId": "sim-user-jordant",
    "gameId": "igdb_7344",
    "igdbId": "7344",
    "title": "Ori and the Blind Forest",
    "platform": "PC (Microsoft Windows)",
    "developer": "Moon Studios",
    "year": "2015",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co1y41.jpg",
    "completionType": "Progress",
    "completionValue": "Mount Nibel Escaped",
    "playerNotes": "Escaped the Ginso Tree. Gorgeous visuals and fluid Metroidvania platforming.",
    "source": "igdb",
    "createdAt": "2026-07-21T01:02:39.340Z"
  },
  {
    "id": "sim-sub-scraped-79",
    "userId": "sim-user-samk",
    "gameId": "igdb_37001",
    "igdbId": "37001",
    "title": "Ori and the Will of the Wisps",
    "platform": "PC (Microsoft Windows)",
    "developer": "Moon Studios",
    "year": "2020",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2e1l.jpg",
    "completionType": "Progress",
    "completionValue": "100% Map",
    "playerNotes": "Improved on the original in every way. The spirit weapon combat is fast and responsive.",
    "source": "igdb",
    "createdAt": "2026-07-21T02:02:40.042Z"
  },
  {
    "id": "sim-sub-scraped-80",
    "userId": "sim-user-elenar",
    "gameId": "igdb_11233",
    "igdbId": "11233",
    "title": "What Remains of Edith Finch",
    "platform": "PC (Microsoft Windows)",
    "developer": "Giant Sparrow",
    "year": "2017",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co1rbj.jpg",
    "completionType": "Progress",
    "completionValue": "Finch Family Tree",
    "playerNotes": "Completed every vignette. The fish factory sequence is unforgettable story design.",
    "source": "igdb",
    "createdAt": "2026-07-21T03:02:40.634Z"
  },
  {
    "id": "sim-sub-scraped-81",
    "userId": "sim-user-alexr",
    "gameId": "igdb_9730",
    "igdbId": "9730",
    "title": "Firewatch",
    "platform": "Linux",
    "developer": "Campo Santo",
    "year": "2016",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/cob1ts.jpg",
    "completionType": "Progress",
    "completionValue": "Summer Over",
    "playerNotes": "Finished Delilah's radio storyline. Beautiful Wyoming wilderness walk with rich dialogue.",
    "source": "igdb",
    "createdAt": "2026-07-21T04:02:41.556Z"
  },
  {
    "id": "sim-sub-scraped-82",
    "userId": "sim-user-mayal",
    "gameId": "igdb_1983",
    "igdbId": "1983",
    "title": "Bastion",
    "platform": "Xbox 360",
    "developer": "Supergiant Games",
    "year": "2011",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co1qlj.jpg",
    "completionType": "Progress",
    "completionValue": "Main Story",
    "playerNotes": "Supergiant's debut with Logan Cunningham's dynamic narrator remains iconic.",
    "source": "igdb",
    "createdAt": "2026-07-21T05:02:42.176Z"
  },
  {
    "id": "sim-sub-scraped-83",
    "userId": "sim-user-jordant",
    "gameId": "igdb_3022",
    "igdbId": "3022",
    "title": "Transistor",
    "platform": "Mac",
    "developer": "Supergiant Games",
    "year": "2014",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/cob23o.jpg",
    "completionType": "Progress",
    "completionValue": "Turn() Execution",
    "playerNotes": "Deep tactical planning with Red's sword in a gorgeous cyberpunk aesthetic.",
    "source": "igdb",
    "createdAt": "2026-07-21T06:02:42.927Z"
  },
  {
    "id": "sim-sub-scraped-84",
    "userId": "sim-user-samk",
    "gameId": "igdb_5601",
    "igdbId": "5601",
    "title": "The Witness",
    "platform": "PC (Microsoft Windows)",
    "developer": "Thekla, Inc",
    "year": "2016",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3hih.jpg",
    "completionType": "Progress",
    "completionValue": "The Challenge",
    "playerNotes": "Solved the secret cavern challenge under the timer. Jonathan Blow's puzzle masterpiece.",
    "source": "igdb",
    "createdAt": "2026-07-21T07:02:43.621Z"
  },
  {
    "id": "sim-sub-scraped-85",
    "userId": "sim-user-elenar",
    "gameId": "igdb_40477",
    "igdbId": "40477",
    "title": "Slay the Spire",
    "platform": "PC (Microsoft Windows)",
    "developer": "Mega Crit Games",
    "year": "2019",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co1iyf.jpg",
    "completionType": "Progress",
    "completionValue": "Heart Defeated (A20)",
    "playerNotes": "Defeated the Heart on Ascension 20. The gold standard for deckbuilding roguelikes.",
    "source": "igdb",
    "createdAt": "2026-07-21T08:02:44.286Z"
  },
  {
    "id": "sim-sub-scraped-86",
    "userId": "sim-user-alexr",
    "gameId": "igdb_26855",
    "igdbId": "26855",
    "title": "Dead Cells",
    "platform": "PC (Microsoft Windows)",
    "developer": "Motion Twin",
    "year": "2018",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co7jfv.jpg",
    "completionType": "Progress",
    "completionValue": "5 Boss Cells Victory",
    "playerNotes": "Beat the Collector on 5 BC. Lightning-fast action platforming.",
    "source": "igdb",
    "createdAt": "2026-07-21T09:02:44.908Z"
  },
  {
    "id": "sim-sub-scraped-87",
    "userId": "sim-user-mayal",
    "gameId": "igdb_14593",
    "igdbId": "14593",
    "title": "Hollow Knight",
    "platform": "Linux",
    "developer": "Team Cherry",
    "year": "2017",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/cobfzp.jpg",
    "completionType": "Progress",
    "completionValue": "Pantheon of Hallownest",
    "playerNotes": "Embrace the Void ending. Hallownest is one of gaming's greatest atmospheric worlds.",
    "source": "igdb",
    "createdAt": "2026-07-21T10:02:45.532Z"
  },
  {
    "id": "sim-sub-scraped-88",
    "userId": "sim-user-jordant",
    "gameId": "igdb_26226",
    "igdbId": "26226",
    "title": "Celeste",
    "platform": "Mac",
    "developer": "Extremely OK Games",
    "year": "2018",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/cob9dh.jpg",
    "completionType": "Progress",
    "completionValue": "Farewell Chapter 9",
    "playerNotes": "Climbed Mount Celeste and completed Chapter 9. Heartfelt story about mental health.",
    "source": "igdb",
    "createdAt": "2026-07-21T11:02:46.303Z"
  },
  {
    "id": "sim-sub-scraped-89",
    "userId": "sim-user-samk",
    "gameId": "igdb_17000",
    "igdbId": "17000",
    "title": "Stardew Valley",
    "platform": "Linux",
    "developer": "ConcernedApe",
    "year": "2016",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/coa93h.jpg",
    "completionType": "Progress",
    "completionValue": "Community Center 100%",
    "playerNotes": "Restored the Community Center and reached Perfection on Grandpa's farm.",
    "source": "igdb",
    "createdAt": "2026-07-21T12:02:47.087Z"
  },
  {
    "id": "sim-sub-scraped-90",
    "userId": "sim-user-elenar",
    "gameId": "igdb_113112",
    "igdbId": "113112",
    "title": "Hades",
    "platform": "PC (Microsoft Windows)",
    "developer": "Supergiant Games",
    "year": "2020",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/cob9kr.jpg",
    "completionType": "Progress",
    "completionValue": "True Family Reunion",
    "playerNotes": "Escaped the Underworld 10 times. Incredible voice acting, story, and roguelite loop.",
    "source": "igdb",
    "createdAt": "2026-07-21T13:02:47.900Z"
  },
  {
    "id": "sim-sub-scraped-91",
    "userId": "sim-user-alexr",
    "gameId": "igdb_9254",
    "igdbId": "9254",
    "title": "Subnautica",
    "platform": "PC (Microsoft Windows)",
    "developer": "Unknown Worlds",
    "year": "2018",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/coa938.jpg",
    "completionType": "Progress",
    "completionValue": "Neptune Rocket Launch",
    "playerNotes": "Cured the bacterium and escaped 4546B. Incredible underwater survival terror.",
    "source": "igdb",
    "createdAt": "2026-07-21T14:02:48.622Z"
  },
  {
    "id": "sim-sub-scraped-92",
    "userId": "sim-user-mayal",
    "gameId": "igdb_11737",
    "igdbId": "11737",
    "title": "Outer Wilds",
    "platform": "PC (Microsoft Windows)",
    "developer": "Mobius Digital",
    "year": "2019",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co65ac.jpg",
    "completionType": "Progress",
    "completionValue": "Eye of the Universe",
    "playerNotes": "Reached the Eye before the sun went supernova. Curiosity-driven exploration at its finest.",
    "source": "igdb",
    "createdAt": "2026-07-21T15:02:49.238Z"
  },
  {
    "id": "sim-sub-scraped-93",
    "userId": "sim-user-jordant",
    "gameId": "igdb_26472",
    "igdbId": "26472",
    "title": "Disco Elysium",
    "platform": "PC (Microsoft Windows)",
    "developer": "ZA/UM",
    "year": "2019",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co1sfj.jpg",
    "completionType": "Progress",
    "completionValue": "Case Closed",
    "playerNotes": "Solved the murder with Kim Kitsuragi. Incredible RPG writing and skill-check system.",
    "source": "igdb",
    "createdAt": "2026-07-21T16:02:50.225Z"
  },
  {
    "id": "sim-sub-scraped-94",
    "userId": "sim-user-samk",
    "gameId": "igdb_72813",
    "igdbId": "72813",
    "title": "Untitled Goose Game",
    "platform": "PC (Microsoft Windows)",
    "developer": "House House",
    "year": "2019",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co1vqc.jpg",
    "completionType": "Progress",
    "completionValue": "To-Do List (Extreme)",
    "playerNotes": "HONK. Tormenting the villagers as a horrible goose is endless fun.",
    "source": "igdb",
    "createdAt": "2026-07-21T17:02:51.386Z"
  },
  {
    "id": "sim-sub-scraped-95",
    "userId": "sim-user-elenar",
    "gameId": "igdb_198499",
    "igdbId": "198499",
    "title": "Chants of Sennaar",
    "platform": "PC (Microsoft Windows)",
    "developer": "Rundisc",
    "year": "2023",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co9mjo.jpg",
    "completionType": "Progress",
    "completionValue": "All Languages Decoded",
    "playerNotes": "Translated all 5 dialects and reconnected the Tower. Brilliant linguistic puzzle game.",
    "source": "igdb",
    "createdAt": "2026-07-21T18:02:52.309Z"
  },
  {
    "id": "sim-sub-scraped-96",
    "userId": "sim-user-alexr",
    "gameId": "igdb_191435",
    "igdbId": "191435",
    "title": "Animal Well",
    "platform": "Nintendo Switch",
    "developer": "Shared Memory",
    "year": "2024",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co4hdh.jpg",
    "completionType": "Progress",
    "completionValue": "Layer 2 Eggs Collected",
    "playerNotes": "Discovered the secrets lurking in the well. Atmospheric pixel-art Metroidvania puzzle box.",
    "source": "igdb",
    "createdAt": "2026-07-21T19:02:53.539Z"
  },
  {
    "id": "sim-sub-scraped-97",
    "userId": "sim-user-mayal",
    "gameId": "igdb_164867",
    "igdbId": "164867",
    "title": "Dredge",
    "platform": "PC (Microsoft Windows)",
    "developer": "Black Salt Games",
    "year": "2023",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co9kyk.jpg",
    "completionType": "Progress",
    "completionValue": "Abyssal Relics Recovered",
    "playerNotes": "Cosmic horror fishing RPG. Dredging the dark ocean at night is deeply unsettling.",
    "source": "igdb",
    "createdAt": "2026-07-21T20:02:54.101Z"
  },
  {
    "id": "sim-sub-scraped-98",
    "userId": "sim-user-jordant",
    "gameId": "igdb_203722",
    "igdbId": "203722",
    "title": "Dave the Diver",
    "platform": "PC (Microsoft Windows)",
    "developer": "MINTROCKET",
    "year": "2023",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/cocdlv.jpg",
    "completionType": "Progress",
    "completionValue": "Bancho Sushi Grand Opening",
    "playerNotes": "Diving by day, managing a booming sushi restaurant by night.",
    "source": "igdb",
    "createdAt": "2026-07-21T21:02:54.730Z"
  },
  {
    "id": "sim-sub-scraped-99",
    "userId": "sim-user-samk",
    "gameId": "igdb_131890",
    "igdbId": "131890",
    "title": "Sea of Stars",
    "platform": "PC (Microsoft Windows)",
    "developer": "Sabotage",
    "year": "2023",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co215b.jpg",
    "completionType": "Progress",
    "completionValue": "True Ending",
    "playerNotes": "Chrono Trigger-inspired retro turn-based RPG with beautiful pixel art and dynamic music.",
    "source": "igdb",
    "createdAt": "2026-07-21T22:02:55.688Z"
  },
  {
    "id": "sim-sub-scraped-100",
    "userId": "sim-user-elenar",
    "gameId": "igdb_111",
    "igdbId": "111",
    "title": "Amnesia: The Dark Descent",
    "platform": "Mac",
    "developer": "Frictional Games",
    "year": "2010",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co1qq5.jpg",
    "completionType": "Progress",
    "completionValue": "Main Story",
    "playerNotes": "Hide in the dark while maintaining sanity. The father of modern survival horror.",
    "source": "igdb",
    "createdAt": "2026-07-21T23:02:56.713Z"
  },
  {
    "id": "sim-sub-scraped-101",
    "userId": "sim-user-chloet",
    "gameId": "igdb_119133",
    "igdbId": "119133",
    "title": "Elden Ring",
    "platform": "PC (Microsoft Windows)",
    "developer": "FromSoftware",
    "year": "2022",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co4jni.jpg",
    "completionType": "Progress",
    "completionValue": "Lord of Frenzied Flame",
    "playerNotes": "Defeated Malenia and conquered the Lands Between. Truly FromSoftware's crowning achievement.",
    "source": "igdb",
    "createdAt": "2026-07-19T22:17:08.790Z"
  },
  {
    "id": "sim-sub-scraped-102",
    "userId": "sim-user-leoc",
    "gameId": "igdb_119171",
    "igdbId": "119171",
    "title": "Baldur's Gate III",
    "platform": "PC (Microsoft Windows)",
    "developer": "Larian Studios",
    "year": "2023",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co670h.jpg",
    "completionType": "Progress",
    "completionValue": "Honor Mode Victory",
    "playerNotes": "Completed Honor Mode with a Tactician build. Unmatched freedom, companions, and CRPG depth.",
    "source": "igdb",
    "createdAt": "2026-07-19T23:17:09.964Z"
  },
  {
    "id": "sim-sub-scraped-103",
    "userId": "sim-user-sarahj",
    "gameId": "igdb_1877",
    "igdbId": "1877",
    "title": "Cyberpunk 2077",
    "platform": "PC (Microsoft Windows)",
    "developer": "CD Projekt RED",
    "year": "2020",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/coaih8.jpg",
    "completionType": "Progress",
    "completionValue": "Phantom Liberty DLC",
    "playerNotes": "Completed Phantom Liberty in Night City. Dogtown and Songbird's story were incredible.",
    "source": "igdb",
    "createdAt": "2026-07-20T00:17:11.138Z"
  },
  {
    "id": "sim-sub-scraped-104",
    "userId": "sim-user-davidk",
    "gameId": "igdb_112875",
    "igdbId": "112875",
    "title": "God of War Ragnarök",
    "platform": "PlayStation 4",
    "developer": "SIE Santa Monica Studio",
    "year": "2022",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/coba3d.jpg",
    "completionType": "Progress",
    "completionValue": "Valhalla Mastered",
    "playerNotes": "100% Valhalla DLC and conquered the Nine Realms. Epic emotional conclusion to Kratos' arc.",
    "source": "igdb",
    "createdAt": "2026-07-20T01:17:11.836Z"
  },
  {
    "id": "sim-sub-scraped-105",
    "userId": "sim-user-sophiam",
    "gameId": "igdb_119388",
    "igdbId": "119388",
    "title": "The Legend of Zelda: Tears of the Kingdom",
    "platform": "Nintendo Switch",
    "developer": "Nintendo EPD Production Group No. 3",
    "year": "2023",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co5vmg.jpg",
    "completionType": "Progress",
    "completionValue": "Main Story",
    "playerNotes": "Built crazy Ultrahand contraptions and explored the Depths. Hyrule expanded brilliantly.",
    "source": "igdb",
    "createdAt": "2026-07-20T02:17:12.674Z"
  },
  {
    "id": "sim-sub-scraped-106",
    "userId": "sim-user-chloet",
    "gameId": "igdb_7346",
    "igdbId": "7346",
    "title": "The Legend of Zelda: Breath of the Wild",
    "platform": "Wii U",
    "developer": "Nintendo EPD Production Group No. 3",
    "year": "2017",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3p2d.jpg",
    "completionType": "Progress",
    "completionValue": "120 Shrines",
    "playerNotes": "Completed all 120 Shrines. Redefined open-world exploration and physics interaction.",
    "source": "igdb",
    "createdAt": "2026-07-20T03:17:13.904Z"
  },
  {
    "id": "sim-sub-scraped-107",
    "userId": "sim-user-leoc",
    "gameId": "igdb_25076",
    "igdbId": "25076",
    "title": "Red Dead Redemption 2",
    "platform": "PlayStation 4",
    "developer": "Rockstar Games",
    "year": "2018",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co1q1f.jpg",
    "completionType": "Progress",
    "completionValue": "100%",
    "playerNotes": "Arthur Morgan's journey is one of the greatest character arcs in entertainment history.",
    "source": "igdb",
    "createdAt": "2026-07-20T04:17:14.518Z"
  },
  {
    "id": "sim-sub-scraped-108",
    "userId": "sim-user-sarahj",
    "gameId": "igdb_1942",
    "igdbId": "1942",
    "title": "The Witcher 3: Wild Hunt",
    "platform": "Xbox One",
    "developer": "CD Projekt RED",
    "year": "2015",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/coaarl.jpg",
    "completionType": "Progress",
    "completionValue": "Blood & Wine DLC",
    "playerNotes": "Finished Toussaint. Geralt's final retirement in Corvo Bianco is the perfect sendoff.",
    "source": "igdb",
    "createdAt": "2026-07-20T05:17:15.275Z"
  },
  {
    "id": "sim-sub-scraped-109",
    "userId": "sim-user-davidk",
    "gameId": "igdb_1020",
    "igdbId": "1020",
    "title": "Grand Theft Auto V",
    "platform": "PlayStation 3",
    "developer": "Rockstar North",
    "year": "2013",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2lbd.jpg",
    "completionType": "Progress",
    "completionValue": "Main Story",
    "playerNotes": "Executed Option C with Michael, Franklin, and Trevor. Los Santos remains iconic.",
    "source": "igdb",
    "createdAt": "2026-07-20T06:17:16.055Z"
  },
  {
    "id": "sim-sub-scraped-110",
    "userId": "sim-user-sophiam",
    "gameId": "igdb_204350",
    "igdbId": "204350",
    "title": "The Last of Us Part I",
    "platform": "PlayStation 5",
    "developer": "Naughty Dog",
    "year": "2022",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/coa1gq.jpg",
    "completionType": "Progress",
    "completionValue": "Grounded Difficulty",
    "playerNotes": "Surviving the journey across post-apocalyptic America with Joel and Ellie on Grounded.",
    "source": "igdb",
    "createdAt": "2026-07-20T07:17:17.284Z"
  },
  {
    "id": "sim-sub-scraped-111",
    "userId": "sim-user-chloet",
    "gameId": "igdb_127044",
    "igdbId": "127044",
    "title": "Marvel's Spider-Man 2",
    "platform": "PlayStation 5",
    "developer": "Insomniac Games",
    "year": "2023",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/cobg1k.jpg",
    "completionType": "Progress",
    "completionValue": "Platinum Trophy",
    "playerNotes": "Swinging through NYC as Peter and Miles with instant fast-travel was unbelievable.",
    "source": "igdb",
    "createdAt": "2026-07-20T08:17:18.137Z"
  },
  {
    "id": "sim-sub-scraped-112",
    "userId": "sim-user-leoc",
    "gameId": "igdb_75235",
    "igdbId": "75235",
    "title": "Ghost of Tsushima",
    "platform": "PlayStation 4",
    "developer": "Sucker Punch Productions",
    "year": "2020",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2crj.jpg",
    "completionType": "Progress",
    "completionValue": "Ghost Armor Unlocked",
    "playerNotes": "Freed Tsushima as Jin Sakai. Kurosawa mode, wind navigation, and samurai combat art.",
    "source": "igdb",
    "createdAt": "2026-07-20T09:17:19.117Z"
  },
  {
    "id": "sim-sub-scraped-113",
    "userId": "sim-user-sarahj",
    "gameId": "igdb_112874",
    "igdbId": "112874",
    "title": "Horizon Forbidden West",
    "platform": "PlayStation 5",
    "developer": "Guerrilla Games",
    "year": "2022",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2gvu.jpg",
    "completionType": "Progress",
    "completionValue": "Burning Shores DLC",
    "playerNotes": "Explored the ruined West Coast and defeated the Horus. Visually stunning world.",
    "source": "igdb",
    "createdAt": "2026-07-20T10:17:19.909Z"
  },
  {
    "id": "sim-sub-scraped-114",
    "userId": "sim-user-davidk",
    "gameId": "igdb_974",
    "igdbId": "974",
    "title": "Resident Evil 4",
    "platform": "Nintendo GameCube",
    "developer": "Capcom Production Studio 4",
    "year": "2005",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2wk8.jpg",
    "completionType": "Progress",
    "completionValue": "S+ Rank Professional",
    "playerNotes": "The 2023 remake modernized the legendary survival action masterpiece flawlessly.",
    "source": "igdb",
    "createdAt": "2026-07-20T11:17:20.422Z"
  },
  {
    "id": "sim-sub-scraped-115",
    "userId": "sim-user-sophiam",
    "gameId": "igdb_55163",
    "igdbId": "55163",
    "title": "Resident Evil Village",
    "platform": "PC (Microsoft Windows)",
    "developer": "Capcom Development Division 1",
    "year": "2021",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/coab9q.jpg",
    "completionType": "Progress",
    "completionValue": "Village of Shadows",
    "playerNotes": "Survived Castle Dimitrescu and the House Beneviento doll horror.",
    "source": "igdb",
    "createdAt": "2026-07-20T12:17:21.583Z"
  },
  {
    "id": "sim-sub-scraped-116",
    "userId": "sim-user-chloet",
    "gameId": "igdb_185246",
    "igdbId": "185246",
    "title": "Alan Wake II",
    "platform": "PC (Microsoft Windows)",
    "developer": "Remedy Entertainment",
    "year": "2023",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co6jar.jpg",
    "completionType": "Progress",
    "completionValue": "Final Draft",
    "playerNotes": "The Dark Place, Saga Anderson, and the Herald of Darkness musical sequence were legendary.",
    "source": "igdb",
    "createdAt": "2026-07-20T13:17:22.299Z"
  },
  {
    "id": "sim-sub-scraped-117",
    "userId": "sim-user-leoc",
    "gameId": "igdb_19564",
    "igdbId": "19564",
    "title": "Death Stranding",
    "platform": "PlayStation 4",
    "developer": "Kojima Productions",
    "year": "2019",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/cobksf.jpg",
    "completionType": "Progress",
    "completionValue": "All Shelters 5-Star",
    "playerNotes": "Reconnected America as Sam Porter Bridges. The Strand genre and soundtrack are unforgettable.",
    "source": "igdb",
    "createdAt": "2026-07-20T14:17:23.191Z"
  },
  {
    "id": "sim-sub-scraped-118",
    "userId": "sim-user-sarahj",
    "gameId": "igdb_36926",
    "igdbId": "36926",
    "title": "Monster Hunter: World",
    "platform": "Xbox One",
    "developer": "Capcom",
    "year": "2018",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co1rst.jpg",
    "completionType": "Progress",
    "completionValue": "High Rank Hunts",
    "playerNotes": "Master Rank 999 with Iceborne. Hunted the black dragon Fatalis after hundreds of hours.",
    "source": "igdb",
    "createdAt": "2026-07-20T15:17:23.705Z"
  },
  {
    "id": "sim-sub-scraped-119",
    "userId": "sim-user-davidk",
    "gameId": "igdb_138950",
    "igdbId": "138950",
    "title": "Monster Hunter Rise",
    "platform": "Nintendo Switch",
    "developer": "Capcom Development Division 2",
    "year": "2021",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3uzk.jpg",
    "completionType": "Progress",
    "completionValue": "Sunbreak Master Rank",
    "playerNotes": "Wirebug mobility and Palamute riding made hunting faster and more dynamic than ever.",
    "source": "igdb",
    "createdAt": "2026-07-20T16:17:24.656Z"
  },
  {
    "id": "sim-sub-scraped-120",
    "userId": "sim-user-sophiam",
    "gameId": "igdb_76882",
    "igdbId": "76882",
    "title": "Sekiro: Shadows Die Twice",
    "platform": "Xbox One",
    "developer": "FromSoftware",
    "year": "2019",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2a23.jpg",
    "completionType": "Progress",
    "completionValue": "Main Story",
    "playerNotes": "Hesitation is defeat. Defeated Isshin Ashina after mastering deflections.",
    "source": "igdb",
    "createdAt": "2026-07-20T17:17:25.525Z"
  },
  {
    "id": "sim-sub-scraped-121",
    "userId": "sim-user-chloet",
    "gameId": "igdb_228542",
    "igdbId": "228542",
    "title": "Armored Core VI: Fires of Rubicon",
    "platform": "PC (Microsoft Windows)",
    "developer": "FromSoftware",
    "year": "2023",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/coc408.jpg",
    "completionType": "Progress",
    "completionValue": "S-Rank All Missions",
    "playerNotes": "Customized the ultimate mech and beat Handler Walter. Fast-paced 3D mech combat.",
    "source": "igdb",
    "createdAt": "2026-07-20T18:17:26.083Z"
  },
  {
    "id": "sim-sub-scraped-122",
    "userId": "sim-user-leoc",
    "gameId": "igdb_114283",
    "igdbId": "114283",
    "title": "Persona 5 Royal",
    "platform": "PlayStation 4",
    "developer": "P Studio",
    "year": "2019",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/cobaqh.jpg",
    "completionType": "Progress",
    "completionValue": "True Ending",
    "playerNotes": "Steal your heart. The third semester storyline with Maruki and Kasumi was phenomenal.",
    "source": "igdb",
    "createdAt": "2026-07-20T19:17:26.796Z"
  },
  {
    "id": "sim-sub-scraped-123",
    "userId": "sim-user-sarahj",
    "gameId": "igdb_133236",
    "igdbId": "133236",
    "title": "Final Fantasy VII Rebirth",
    "platform": "PlayStation 5",
    "developer": "Square Enix Creative Business Unit I",
    "year": "2024",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/cob9k6.jpg",
    "completionType": "Progress",
    "completionValue": "Hard Mode Campaign",
    "playerNotes": "Expanded Gaia with incredible combat depth, synergy abilities, and open regions.",
    "source": "igdb",
    "createdAt": "2026-07-20T20:17:27.653Z"
  },
  {
    "id": "sim-sub-scraped-124",
    "userId": "sim-user-davidk",
    "gameId": "igdb_31551",
    "igdbId": "31551",
    "title": "Final Fantasy XVI",
    "platform": "PlayStation 5",
    "developer": "Square Enix Creative Business Unit III",
    "year": "2023",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/cobd9i.jpg",
    "completionType": "Progress",
    "completionValue": "Final Fantasy Mode",
    "playerNotes": "Clive Rosfield's Eikon battles against Bahamut and Titan were jaw-dropping spectacles.",
    "source": "igdb",
    "createdAt": "2026-07-20T21:17:28.350Z"
  },
  {
    "id": "sim-sub-scraped-125",
    "userId": "sim-user-sophiam",
    "gameId": "igdb_115060",
    "igdbId": "115060",
    "title": "Dragon's Dogma II",
    "platform": "PC (Microsoft Windows)",
    "developer": "Capcom Development Division 1",
    "year": "2024",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co833w.jpg",
    "completionType": "Progress",
    "completionValue": "Unmoored World Escaped",
    "playerNotes": "Vocation combat, Pawn AI companion system, and emergent monster battles.",
    "source": "igdb",
    "createdAt": "2026-07-20T22:17:28.965Z"
  },
  {
    "id": "sim-sub-scraped-126",
    "userId": "sim-user-chloet",
    "gameId": "igdb_236663",
    "igdbId": "236663",
    "title": "Metroid Prime Remastered",
    "platform": "Nintendo Switch",
    "developer": "Retro Studios",
    "year": "2023",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/cobbn9.jpg",
    "completionType": "Progress",
    "completionValue": "100% Scan Log",
    "playerNotes": "Tallon IV remastered in gorgeous 60fps with dual-stick controls. Immersive isolation.",
    "source": "igdb",
    "createdAt": "2026-07-20T23:17:29.509Z"
  },
  {
    "id": "sim-sub-scraped-127",
    "userId": "sim-user-leoc",
    "gameId": "igdb_15698",
    "igdbId": "15698",
    "title": "Metroid Dread",
    "platform": "Nintendo Switch",
    "developer": "Nintendo Entertainment Planning & Development",
    "year": "2021",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/coba9g.jpg",
    "completionType": "Progress",
    "completionValue": "Dread Mode",
    "playerNotes": "Escaped the E.M.M.I. robots on planet ZDR. Lightning-fast 2D Metroid action.",
    "source": "igdb",
    "createdAt": "2026-07-21T00:17:29.976Z"
  },
  {
    "id": "sim-sub-scraped-128",
    "userId": "sim-user-sarahj",
    "gameId": "igdb_254339",
    "igdbId": "254339",
    "title": "Super Mario Bros. Wonder",
    "platform": "Nintendo Switch",
    "developer": "Nintendo EPD Production Group No. 10",
    "year": "2023",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co6nnl.jpg",
    "completionType": "Progress",
    "completionValue": "Special World 100%",
    "playerNotes": "Wonder Flowers transformed levels into creative trippy platforming joy.",
    "source": "igdb",
    "createdAt": "2026-07-21T01:17:30.485Z"
  },
  {
    "id": "sim-sub-scraped-129",
    "userId": "sim-user-davidk",
    "gameId": "igdb_26758",
    "igdbId": "26758",
    "title": "Super Mario Odyssey",
    "platform": "Nintendo Switch",
    "developer": "Nintendo EPD Production Group No. 8",
    "year": "2017",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co1mxf.jpg",
    "completionType": "Progress",
    "completionValue": "880 Power Moons",
    "playerNotes": "Captured everything with Cappy. New Donk City and the Metro Kingdom jump song!",
    "source": "igdb",
    "createdAt": "2026-07-21T02:17:31.040Z"
  },
  {
    "id": "sim-sub-scraped-130",
    "userId": "sim-user-sophiam",
    "gameId": "igdb_90101",
    "igdbId": "90101",
    "title": "Super Smash Bros. Ultimate",
    "platform": "Nintendo Switch",
    "developer": "Sora",
    "year": "2018",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2255.jpg",
    "completionType": "Progress",
    "completionValue": "World of Light",
    "playerNotes": "Everyone is here! 89 fighters, hundreds of stages, and endless competitive fun.",
    "source": "igdb",
    "createdAt": "2026-07-21T03:17:31.573Z"
  },
  {
    "id": "sim-sub-scraped-131",
    "userId": "sim-user-chloet",
    "gameId": "igdb_26764",
    "igdbId": "26764",
    "title": "Mario Kart 8 Deluxe",
    "platform": "Nintendo Switch",
    "developer": "Nintendo EPD Production Group No. 9",
    "year": "2017",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co213p.jpg",
    "completionType": "Progress",
    "completionValue": "3-Star All 96 Courses",
    "playerNotes": "Booster Course Pass added 48 remastered tracks. The ultimate party kart racer.",
    "source": "igdb",
    "createdAt": "2026-07-21T04:17:32.129Z"
  },
  {
    "id": "sim-sub-scraped-132",
    "userId": "sim-user-leoc",
    "gameId": "igdb_109462",
    "igdbId": "109462",
    "title": "Animal Crossing: New Horizons",
    "platform": "Nintendo Switch",
    "developer": "Nintendo EPD Production Group No. 5",
    "year": "2020",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3wls.jpg",
    "completionType": "Progress",
    "completionValue": "5-Star Island Rating",
    "playerNotes": "Designed a paradise island resort. Teraforming and decorating with villager friends.",
    "source": "igdb",
    "createdAt": "2026-07-21T05:17:33.257Z"
  },
  {
    "id": "sim-sub-scraped-133",
    "userId": "sim-user-sarahj",
    "gameId": "igdb_96437",
    "igdbId": "96437",
    "title": "Starfield",
    "platform": "PC (Microsoft Windows)",
    "developer": "Bethesda Game Studios",
    "year": "2023",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co39vv.jpg",
    "completionType": "Progress",
    "completionValue": "NG+ 10 Starborn",
    "playerNotes": "Explored the Settled Systems, built custom starships, and unraveled the Artifacts.",
    "source": "igdb",
    "createdAt": "2026-07-21T06:17:34.249Z"
  },
  {
    "id": "sim-sub-scraped-134",
    "userId": "sim-user-davidk",
    "gameId": "igdb_141503",
    "igdbId": "141503",
    "title": "Forza Horizon 5",
    "platform": "Xbox Series X|S",
    "developer": "Playground Games",
    "year": "2021",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3ofx.jpg",
    "completionType": "Progress",
    "completionValue": "Hall of Fame Unlocked",
    "playerNotes": "Racing through Mexico's vibrant biomes, volcanoes, and seasonal storms in 4K.",
    "source": "igdb",
    "createdAt": "2026-07-21T07:17:35.101Z"
  },
  {
    "id": "sim-sub-scraped-135",
    "userId": "sim-user-sophiam",
    "gameId": "igdb_103281",
    "igdbId": "103281",
    "title": "Halo Infinite",
    "platform": "Xbox One",
    "developer": "343 Industries",
    "year": "2021",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2dto.jpg",
    "completionType": "Progress",
    "completionValue": "Laso Campaign",
    "playerNotes": "Grappleshot mobility on Zeta Halo made chief feel like a true Spartan god.",
    "source": "igdb",
    "createdAt": "2026-07-21T08:17:36.226Z"
  },
  {
    "id": "sim-sub-scraped-136",
    "userId": "sim-user-chloet",
    "gameId": "igdb_103298",
    "igdbId": "103298",
    "title": "Doom Eternal",
    "platform": "PC (Microsoft Windows)",
    "developer": "id Software",
    "year": "2020",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3p5n.jpg",
    "completionType": "Progress",
    "completionValue": "Ultra-Nightmare",
    "playerNotes": "The Slayer's push-forward combat loop with the flame belch and chainsaw.",
    "source": "igdb",
    "createdAt": "2026-07-21T09:17:36.942Z"
  },
  {
    "id": "sim-sub-scraped-137",
    "userId": "sim-user-leoc",
    "gameId": "igdb_233585",
    "igdbId": "233585",
    "title": "Hi-Fi Rush",
    "platform": "PC (Microsoft Windows)",
    "developer": "Tango Gameworks",
    "year": "2023",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co6219.jpg",
    "completionType": "Progress",
    "completionValue": "S-Rank Rhythm Master",
    "playerNotes": "Chai fighting corporate overlords on the beat. cel-shaded rhythm action surprise drop.",
    "source": "igdb",
    "createdAt": "2026-07-21T10:17:37.869Z"
  },
  {
    "id": "sim-sub-scraped-138",
    "userId": "sim-user-sarahj",
    "gameId": "igdb_148241",
    "igdbId": "148241",
    "title": "Lies of P",
    "platform": "PC (Microsoft Windows)",
    "developer": "Round8 Studio",
    "year": "2023",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co6lxr.jpg",
    "completionType": "Progress",
    "completionValue": "Rise of P Ending",
    "playerNotes": "Pinocchio in a dark Belle Époque puppet nightmare with weapon-assembly customization.",
    "source": "igdb",
    "createdAt": "2026-07-21T11:17:38.479Z"
  },
  {
    "id": "sim-sub-scraped-139",
    "userId": "sim-user-davidk",
    "gameId": "igdb_136879",
    "igdbId": "136879",
    "title": "Black Myth: Wukong",
    "platform": "PC (Microsoft Windows)",
    "developer": "Game Science",
    "year": "2024",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co8h3y.jpg",
    "completionType": "Progress",
    "completionValue": "Great Sage Equal to Heaven",
    "playerNotes": "Journey to the West as the Destined One. Epic staff stances and transformation spells.",
    "source": "igdb",
    "createdAt": "2026-07-21T12:17:39.366Z"
  },
  {
    "id": "sim-sub-scraped-140",
    "userId": "sim-user-sophiam",
    "gameId": "igdb_250616",
    "igdbId": "250616",
    "title": "Helldivers 2",
    "platform": "PlayStation 5",
    "developer": "Arrowhead Game Studios",
    "year": "2024",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/coabbf.jpg",
    "completionType": "Progress",
    "completionValue": "Helldive Difficulty",
    "playerNotes": "For Super Earth and Managed Democracy! Calling down orbital stratagems against Automatons.",
    "source": "igdb",
    "createdAt": "2026-07-21T13:17:40.220Z"
  },
  {
    "id": "sim-sub-scraped-141",
    "userId": "sim-user-chloet",
    "gameId": "igdb_151665",
    "igdbId": "151665",
    "title": "Palworld",
    "platform": "PC (Microsoft Windows)",
    "developer": "PocketPair",
    "year": "2026",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co7n02.jpg",
    "completionType": "Progress",
    "completionValue": "All Paldeck Entries",
    "playerNotes": "Base building, Pal automation, and catching elemental Pals across the islands.",
    "source": "igdb",
    "createdAt": "2026-07-21T14:17:40.948Z"
  },
  {
    "id": "sim-sub-scraped-142",
    "userId": "sim-user-leoc",
    "gameId": "igdb_191692",
    "igdbId": "191692",
    "title": "Street Fighter 6",
    "platform": "Xbox Series X|S",
    "developer": "Capcom",
    "year": "2023",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co9wxo.jpg",
    "completionType": "Progress",
    "completionValue": "Master Rank World Tour",
    "playerNotes": "Drive Gauge system and World Tour avatar mode revitalized the fighting game scene.",
    "source": "igdb",
    "createdAt": "2026-07-21T15:17:42.063Z"
  },
  {
    "id": "sim-sub-scraped-143",
    "userId": "sim-user-sarahj",
    "gameId": "igdb_217590",
    "igdbId": "217590",
    "title": "Tekken 8",
    "platform": "Xbox Series X|S",
    "developer": "Bandai Namco Studios",
    "year": "2024",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co7lbb.jpg",
    "completionType": "Progress",
    "completionValue": "Main Story",
    "playerNotes": "Heat System aggression and Jin vs Kazuya climax in a gorgeous Unreal Engine 5 fighter.",
    "source": "igdb",
    "createdAt": "2026-07-21T16:17:42.763Z"
  },
  {
    "id": "sim-sub-scraped-144",
    "userId": "sim-user-davidk",
    "gameId": "igdb_125764",
    "igdbId": "125764",
    "title": "Guilty Gear: Strive",
    "platform": "PlayStation 5",
    "developer": "Arc System Works",
    "year": "2021",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2lby.jpg",
    "completionType": "Progress",
    "completionValue": "Celestial Floor Reached",
    "playerNotes": "Stunning anime visuals, Daisuke Ishiwatari's rock soundtrack, and Wall Break mechanics.",
    "source": "igdb",
    "createdAt": "2026-07-21T17:17:43.425Z"
  },
  {
    "id": "sim-sub-scraped-145",
    "userId": "sim-user-sophiam",
    "gameId": "igdb_135243",
    "igdbId": "135243",
    "title": "It Takes Two",
    "platform": "PC (Microsoft Windows)",
    "developer": "Hazelight Studios",
    "year": "2021",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/cob22v.jpg",
    "completionType": "Progress",
    "completionValue": "Main Story",
    "playerNotes": "Co-op perfection where every single chapter introduces a completely new gameplay mechanic.",
    "source": "igdb",
    "createdAt": "2026-07-21T18:17:44.214Z"
  },
  {
    "id": "sim-sub-scraped-146",
    "userId": "sim-user-chloet",
    "gameId": "igdb_152242",
    "igdbId": "152242",
    "title": "A Plague Tale: Requiem",
    "platform": "Xbox Series X|S",
    "developer": "Asobo Studio",
    "year": "2022",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co5pwb.jpg",
    "completionType": "Progress",
    "completionValue": "Main Story",
    "playerNotes": "Amicia and Hugo's heartbreaking journey across medieval France infested with rat swarms.",
    "source": "igdb",
    "createdAt": "2026-07-21T19:17:44.929Z"
  },
  {
    "id": "sim-sub-scraped-147",
    "userId": "sim-user-leoc",
    "gameId": "igdb_225582",
    "igdbId": "225582",
    "title": "Control Resonant",
    "platform": "PlayStation 5",
    "developer": "Remedy Entertainment",
    "year": "2026",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/coc64f.jpg",
    "completionType": "Progress",
    "completionValue": "Executive Director",
    "playerNotes": "Levitating and throwing objects with telekinesis through the shifting Oldest House.",
    "source": "igdb",
    "createdAt": "2026-07-21T20:17:45.808Z"
  },
  {
    "id": "sim-sub-scraped-148",
    "userId": "sim-user-sarahj",
    "gameId": "igdb_134584",
    "igdbId": "134584",
    "title": "Returnal",
    "platform": "PlayStation 5",
    "developer": "Housemarque",
    "year": "2021",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3wc1.jpg",
    "completionType": "Progress",
    "completionValue": "Act 3 Sunface Fragments",
    "playerNotes": "Selene trapped in a dark psychological roguelike bullet-hell loop on Atropos.",
    "source": "igdb",
    "createdAt": "2026-07-21T21:17:46.479Z"
  },
  {
    "id": "sim-sub-scraped-149",
    "userId": "sim-user-davidk",
    "gameId": "igdb_5619",
    "igdbId": "5619",
    "title": "Demon's Souls",
    "platform": "PlayStation 3",
    "developer": "FromSoftware",
    "year": "2009",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co27sk.jpg",
    "completionType": "Progress",
    "completionValue": "Pure White World Tendency",
    "playerNotes": "Bluepoint's gorgeous PS5 remake set the standard for next-gen visual fidelity.",
    "source": "igdb",
    "createdAt": "2026-07-21T22:17:47.494Z"
  },
  {
    "id": "sim-sub-scraped-150",
    "userId": "sim-user-sophiam",
    "gameId": "igdb_201156",
    "igdbId": "201156",
    "title": "Star Wars Jedi: Survivor",
    "platform": "PC (Microsoft Windows)",
    "developer": "Respawn Entertainment",
    "year": "2023",
    "imageUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co5uzk.jpg",
    "completionType": "Progress",
    "completionValue": "Grandmaster Difficulty",
    "playerNotes": "Cal Kestis mastering 5 lightsaber stances and exploring Koboh's vast open zones.",
    "source": "igdb",
    "createdAt": "2026-07-21T23:17:48.207Z"
  }
];
